[pytest]
minversion = 7.0
addopts = --cov=src --cov-report term-missing
pythonpath = src
testpaths = tests
env =
    DEBUG=False
    POD_NAME=test-pod
    DB_USER=None
    DB_PASS=None
    DB_HOST=None
    DB_PORT=None
    DB_DATABASE=None